model_path: yolo11m.pt
data_yaml: configs/data_depth.yaml
training:
  epochs: 40
  imgsz: 640
  patience: 15
  batch_size: 8
  save_period: 10
  workers: 4
device: cuda
validation:
  conf_thres: 0.25
  iou_thres: 0.45
  max_det: 300
project: runs/detect
name: train_depth
