# 服务器配置
server:
  url: 'http://localhost:5000'
  host: '0.0.0.0'
  port: 5000

# 跟踪器配置
tracker:
  required_stable_frames: 3
  mjpg_quality: 95
  display_window: true
  confidence_threshold: 0.5
  # 双模型特有配置
  depth_model_path: 'runs/detect/depth_train7/weights/best.pt'
  fusion_weights:
    rgb: 0.8
    depth: 0.2

# 摄像头设置
camera:
  source: 0  # 0 表示默认摄像头
  settings:
    CAP_PROP_FRAME_WIDTH: 640
    CAP_PROP_FRAME_HEIGHT: 480
    CAP_PROP_FPS: 30
    CAP_PROP_BRIGHTNESS: 100
    CAP_PROP_CONTRAST: 100
    CAP_PROP_SATURATION: 100

# 日志配置
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: 'logs/tracker.log'